### ISSUE TITLE
No GPT4 Turbo Yet

### ISSUE THREAD

**Issue by AlexanderBZ** [SwiftBeta/SwiftOpenAI#31]

**Comment by SwiftBeta** [comment]
Hello Alexander,

GPT-4 Turbo models have been available since the release of version 0.9.0, as noted in this [commit](https://github.com/SwiftBeta/SwiftOpenAI/commit/6d15a5ccf9fbd72a0a1bf309c062a3fa76c04267#diff-8406f721e7b5d9949079dbf71e7c8013f348064b87ffbcf15571b96ec9e77e8aR33). 

According to the [documentation](https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo), the features remain the same.
